# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveExceptionModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
                ('method_name', models.CharField(max_length=255)),
                ('route', models.TextField()),
                ('log_data', models.BinaryField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveHttpHostModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('checked_count', models.IntegerField(default=0)),
                ('random_id', models.CharField(default='', max_length=6)),
                ('secure', models.BooleanField(default=False)),
                ('port', models.IntegerField()),
                ('framework', models.CharField(max_length=255)),
                ('report_type', models.IntegerField(choices=[(0, 'exception')], default=0)),
                ('package_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivePackageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommonHostModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('checked_count', models.IntegerField(default=0)),
                ('random_id', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='CommonMessageModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Custom'), (1, 'Brief Message'), (2, 'Detailed Message'), (3, 'Auto Message')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Custom'), (1, 'Success'), (2, 'Warning'), (3, 'Notice'), (4, 'Error')], default=0)),
                ('content', models.TextField(default='')),
                ('power', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonOriginModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=900)),
                ('secret', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CommonReportModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Custom'), (1, 'Ping Success'), (2, 'Ping Delay'), (3, 'Http Success'), (4, 'Http Delay'), (5, 'Response Success'), (6, 'Response Delay'), (7, 'Exceptions')], default=0)),
                ('value', models.FloatField(default=0.0)),
                ('comments', models.TextField(default='No comment')),
            ],
        ),
        migrations.CreateModel(
            name='HttpDataModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('succeed', models.BooleanField(default=False)),
                ('code', models.IntegerField(default=200)),
                ('header', models.TextField()),
                ('delay_std', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HttpHostModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('checked_count', models.IntegerField(default=0)),
                ('random_id', models.CharField(default='', max_length=6)),
                ('secure', models.BooleanField(default=False)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HttpOriginModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=900)),
                ('secret', models.CharField(default='', max_length=32)),
                ('ua', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PingDataModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('transmitted_times', models.IntegerField()),
                ('received_times', models.IntegerField()),
                ('delay_min', models.FloatField()),
                ('delay_avg', models.FloatField()),
                ('delay_max', models.FloatField()),
                ('delay_std', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PingHostModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('checked_count', models.IntegerField(default=0)),
                ('random_id', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PingOriginModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=900)),
                ('secret', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RespDataModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('succeed', models.BooleanField(default=False)),
                ('code', models.IntegerField(default=200)),
                ('header', models.TextField()),
                ('delay_std', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('passed', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=0)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RespHostModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('checked_count', models.IntegerField(default=0)),
                ('random_id', models.CharField(default='', max_length=6)),
                ('url', models.CharField(max_length=255)),
                ('expected_contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RespOriginModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=900)),
                ('secret', models.CharField(default='', max_length=32)),
                ('ua', models.CharField(default='', max_length=512)),
                ('bandwidth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfigCategoryModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfigModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=256)),
                ('comments', models.TextField(blank=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.SiteConfigCategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatusModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Custom'), (1, 'Success'), (2, 'Warning'), (3, 'Notice'), (4, 'Error')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveExceptionPackageModel',
            fields=[
                ('activepackagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.ActivePackageModel')),
            ],
            bases=('hello_app.activepackagemodel',),
        ),
        migrations.CreateModel(
            name='SiteMessageModel',
            fields=[
                ('commonmessagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.CommonMessageModel')),
            ],
            bases=('hello_app.commonmessagemodel',),
        ),
        migrations.CreateModel(
            name='SiteReportModel',
            fields=[
                ('commonreportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.CommonReportModel')),
                ('caches', models.TextField(blank=True)),
            ],
            bases=('hello_app.commonreportmodel',),
        ),
        migrations.AddField(
            model_name='respdatamodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.RespHostModel'),
        ),
        migrations.AddField(
            model_name='respdatamodel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.RespOriginModel'),
        ),
        migrations.AddField(
            model_name='pingdatamodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.PingHostModel'),
        ),
        migrations.AddField(
            model_name='pingdatamodel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.PingOriginModel'),
        ),
        migrations.AddField(
            model_name='httpdatamodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.HttpHostModel'),
        ),
        migrations.AddField(
            model_name='httpdatamodel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.HttpOriginModel'),
        ),
        migrations.AddField(
            model_name='activeexceptionmodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.ActiveHttpHostModel'),
        ),
    ]
