# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonHostModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonOriginModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HttpDataModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('succeed', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
                ('header', models.TextField()),
                ('delay_std', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PingDataModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('transmitted_times', models.IntegerField()),
                ('received_times', models.IntegerField()),
                ('delay_min', models.FloatField()),
                ('delay_avg', models.FloatField()),
                ('delay_max', models.FloatField()),
                ('delay_std', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HttpHostModel',
            fields=[
                ('commonhostmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.CommonHostModel')),
                ('secure', models.BooleanField(default=False)),
                ('port', models.IntegerField()),
            ],
            bases=('hello_app.commonhostmodel',),
        ),
        migrations.CreateModel(
            name='HttpOriginModel',
            fields=[
                ('commonoriginmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.CommonOriginModel')),
                ('ua', models.CharField(default='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36', max_length=512)),
            ],
            bases=('hello_app.commonoriginmodel',),
        ),
        migrations.CreateModel(
            name='PingHostModel',
            fields=[
                ('commonhostmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.CommonHostModel')),
            ],
            bases=('hello_app.commonhostmodel',),
        ),
        migrations.CreateModel(
            name='PingOriginModel',
            fields=[
                ('commonoriginmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.CommonOriginModel')),
            ],
            bases=('hello_app.commonoriginmodel',),
        ),
        migrations.AddField(
            model_name='pingdatamodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.PingHostModel'),
        ),
        migrations.AddField(
            model_name='pingdatamodel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.PingOriginModel'),
        ),
        migrations.AddField(
            model_name='httpdatamodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.HttpHostModel'),
        ),
        migrations.AddField(
            model_name='httpdatamodel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.PingOriginModel'),
        ),
    ]
