# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resphostmodel',
            old_name='expected_method',
            new_name='match_method',
        ),
        migrations.RemoveField(
            model_name='resphostmodel',
            name='expected_contents',
        ),
        migrations.AddField(
            model_name='resphostmodel',
            name='expected_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resphostmodel',
            name='expected_headers',
            field=models.TextField(blank=True),
        ),
    ]
