# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonReportModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Custom'), (1, 'PingSuccess'), (2, 'PingDelay'), (3, 'HttpSuccess'), (4, 'HttpDelay'), (5, 'RespSuccess'), (6, 'RespDelay'), (7, 'Exceptions')], default=0)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='httpdatamodel',
            name='code',
            field=models.IntegerField(default=200),
        ),
    ]
