# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activehttphostmodel',
            name='checked_count',
        ),
        migrations.RemoveField(
            model_name='commonhostmodel',
            name='checked_count',
        ),
        migrations.RemoveField(
            model_name='commonoriginmodel',
            name='sent_count',
        ),
        migrations.RemoveField(
            model_name='httphostmodel',
            name='checked_count',
        ),
        migrations.RemoveField(
            model_name='httporiginmodel',
            name='sent_count',
        ),
        migrations.RemoveField(
            model_name='pinghostmodel',
            name='checked_count',
        ),
        migrations.RemoveField(
            model_name='pingoriginmodel',
            name='sent_count',
        ),
        migrations.RemoveField(
            model_name='resphostmodel',
            name='checked_count',
        ),
        migrations.RemoveField(
            model_name='resporiginmodel',
            name='sent_count',
        ),
    ]
