# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0002_auto_20160205_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReportModel',
            fields=[
                ('commonreportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.CommonReportModel')),
                ('caches', models.TextField()),
            ],
            bases=('hello_app.commonreportmodel',),
        ),
        migrations.AddField(
            model_name='commonreportmodel',
            name='comments',
            field=models.TextField(default='No comment'),
        ),
        migrations.AlterField(
            model_name='commonhostmodel',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='httpdatamodel',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pingdatamodel',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
