# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0002_auto_20160320_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonoriginmodel',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='httporiginmodel',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='pingoriginmodel',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='resporiginmodel',
            name='frequency',
        ),
        migrations.AddField(
            model_name='commonhostmodel',
            name='frequency',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='httphostmodel',
            name='frequency',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='pinghostmodel',
            name='frequency',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='resphostmodel',
            name='frequency',
            field=models.IntegerField(default=900),
        ),
    ]
