# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0003_auto_20160206_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMessageModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[('0', 'Custom'), ('1', 'Brief Message'), ('2', 'Detailed Message'), ('3', 'Internal Message')], default=0)),
                ('status', models.IntegerField(choices=[('0', 'Custom'), ('1', 'Success'), ('2', 'Warning'), ('3', 'Notice'), ('4', 'Error')], default=0)),
                ('power', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
