# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0003_auto_20160321_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHourlyReportModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Custom'), (1, 'Ping Success'), (2, 'Ping Delay'), (3, 'Http Success'), (4, 'Http Delay'), (5, 'Response Success'), (6, 'Response Delay'), (7, 'Exceptions')], default=0)),
                ('value', models.FloatField(default=0.0)),
                ('comments', models.TextField(default='No comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='sitereportmodel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='sitereportmodel',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='commonmessagemodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='commonmessagemodel',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='HttpHourlyReportModel',
            fields=[
                ('sitehourlyreportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.SiteHourlyReportModel')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.HttpHostModel')),
            ],
            bases=('hello_app.sitehourlyreportmodel',),
        ),
        migrations.CreateModel(
            name='PingHourlyReportModel',
            fields=[
                ('sitehourlyreportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.SiteHourlyReportModel')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.PingHostModel')),
            ],
            bases=('hello_app.sitehourlyreportmodel',),
        ),
        migrations.CreateModel(
            name='RespHourlyReportModel',
            fields=[
                ('sitehourlyreportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_app.SiteHourlyReportModel')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.RespHostModel')),
            ],
            bases=('hello_app.sitehourlyreportmodel',),
        ),
    ]
