# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0005_sitemessagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmessagemodel',
            name='content',
            field=models.TextField(default='All systems reporting at 100%'),
            preserve_default=False,
        ),
    ]
