# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0006_commonmessagemodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=256)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='commonhostmodel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commonmessagemodel',
            name='content',
            field=models.TextField(default=b'None'),
        ),
        migrations.AlterField(
            model_name='commonmessagemodel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commonmessagemodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Custom'), (1, 'Success'), (2, 'Warning'), (3, 'Notice'), (4, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='commonmessagemodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'Custom'), (1, 'Brief Message'), (2, 'Detailed Message'), (3, 'Internal Message')], default=0),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commonreportmodel',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='httporiginmodel',
            name='ua',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='sitereportmodel',
            name='caches',
            field=models.TextField(blank=True),
        ),
    ]
