# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0007_auto_20160208_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatusModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Custom'), (1, 'Success'), (2, 'Warning'), (3, 'Notice'), (4, 'Error')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commonmessagemodel',
            name='content',
            field=models.TextField(default=b'All systems reporting at 100%'),
        ),
        migrations.AlterField(
            model_name='commonmessagemodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'Custom'), (1, 'Brief Message'), (2, 'Detailed Message'), (3, 'Auto Message')], default=0),
        ),
        migrations.AlterField(
            model_name='httporiginmodel',
            name='ua',
            field=models.CharField(default='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36', max_length=512),
        ),
    ]
